# Generated by Django 5.0.7 on 2024-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('place', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='stadium')),
            ],
        ),
    ]
