# Generated by Django 5.0.7 on 2024-07-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grounds',
            new_name='Ground',
        ),
    ]
