# Generated by Django 5.0.7 on 2024-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_grounds_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stadium'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
