# Generated by Django 5.0.7 on 2024-08-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_ground_address_alter_ground_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_1', models.TextField(blank=True, null=True)),
                ('point_2', models.TextField(blank=True, null=True)),
                ('point_3', models.TextField(blank=True, null=True)),
                ('point_4', models.TextField(blank=True, null=True)),
                ('point_5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_1', models.TextField(blank=True, null=True)),
                ('point_2', models.TextField(blank=True, null=True)),
                ('point_3', models.TextField(blank=True, null=True)),
                ('point_4', models.TextField(blank=True, null=True)),
                ('point_5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
