# Generated by Django 5.0.7 on 2024-08-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='point_1',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='vision',
            old_name='point_1',
            new_name='vision',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='point_2',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='point_3',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='point_4',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='point_5',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='point_2',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='point_3',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='point_4',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='point_5',
        ),
    ]
