# Generated by Django 5.0.7 on 2024-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_delete_mission_delete_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='sports',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='surface',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
