# Generated by Django 5.0.7 on 2024-08-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_ground_operator_ground_sports_ground_surface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
