# Generated by Django 5.0.7 on 2024-08-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_ground_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='place',
            new_name='country',
        ),
    ]
