# Generated by Django 5.0.7 on 2024-08-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_place_ground_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='ground',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='stadium'),
        ),
        migrations.AddField(
            model_name='ground',
            name='suites',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='web_wiki',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
