# Generated by Django 5.0.7 on 2024-08-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_suites_ground_suite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='type',
            new_name='ground_type',
        ),
    ]
