# Generated by Django 5.0.7 on 2024-08-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_ground_locality_ground_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='summary',
        ),
        migrations.AddField(
            model_name='ground',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
