# Generated by Django 5.0.7 on 2024-08-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_ground_summary_ground_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='stadium'),
        ),
    ]
