# Generated by Django 5.0.7 on 2024-08-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_ground_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='image_3',
        ),
    ]
