# Generated by Django 5.0.7 on 2024-08-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_ground_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='ground_type',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='surface',
        ),
        migrations.RemoveField(
            model_name='ground',
            name='web_wiki',
        ),
    ]
