# Generated by Django 5.0.7 on 2024-08-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_ground_agent_ground_image_2_ground_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='web',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
