# Generated by Django 5.0.7 on 2024-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_ground_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
