# Generated by Django 5.0.7 on 2024-08-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
