# Generated by Django 5.0.7 on 2024-08-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_agent_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='summary',
            new_name='description',
        ),
    ]
