# Generated by Django 5.0.7 on 2024-08-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_rename_map_ground_map_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='social_3',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='social_4',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='website',
        ),
    ]
