# Generated by Django 5.0.7 on 2024-08-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_agent_prof_remove_agent_social_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='social_1',
            new_name='Id_no',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='social_2',
            new_name='license_no',
        ),
    ]
