# Generated by Django 5.0.7 on 2024-08-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_social_1_agent_id_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='license_no',
            new_name='proffession',
        ),
    ]
