# Generated by Django 5.0.7 on 2024-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_rename_proffession_agent_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
