# Generated by Django 5.0.7 on 2024-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_rename_careers_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
