# Generated by Django 5.0.7 on 2024-08-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_career_description_alter_career_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
