# Generated by Django 5.0.7 on 2024-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_career_place_career_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='career',
            new_name='name',
        ),
    ]
