# Generated by Django 5.0.7 on 2024-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_alter_career_closing_date_alter_career_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
