# Generated by Django 5.0.7 on 2024-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_partners_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
