# Generated by Django 5.0.7 on 2024-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_ground_capacity_alter_ground_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Id_no',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='occupation',
        ),
    ]
