# Generated by Django 5.0.7 on 2024-08-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_rename_whatsapp_agent_applicant_remove_agent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='rental',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
