# Generated by Django 5.0.7 on 2024-08-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_ground_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
