# Generated by Django 5.0.7 on 2024-09-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_alter_agent_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='rental',
            new_name='booking_advance',
        ),
    ]
