# Generated by Django 5.0.7 on 2024-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_rename_rental_ground_booking_advance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ground',
            old_name='booking_advance',
            new_name='booking',
        ),
    ]
