# Generated by Django 5.0.7 on 2024-08-02 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeedback',
            old_name='feed',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='mail',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='sub',
            new_name='subject',
        ),
    ]
