# Generated by Django 5.0.7 on 2024-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_userfeedback_image_userfeedback_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='feeds')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='profession',
        ),
    ]
