# Generated by Django 5.0.7 on 2024-08-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_testimonialdb_delete_viewfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFeedback',
            new_name='Feedback',
        ),
    ]
