# Generated by Django 5.0.7 on 2024-08-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_rename_userfeedback_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestimonialDb',
            new_name='Testimonial',
        ),
    ]
