# Generated by Django 5.0.7 on 2024-08-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_rename_testimonialdb_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_agent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applied_agent',
            name='occupation',
        ),
    ]
