# Generated by Django 5.0.7 on 2024-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_remove_applied_agent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_agent',
            name='Id_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
