# Generated by Django 5.0.7 on 2024-08-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_rename_relocate_career_applications_ready_to_relocate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_applications',
            old_name='resume',
            new_name='upload_resume',
        ),
    ]
