# Generated by Django 5.0.7 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_rename_upload_resume_career_applications_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_applications',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
