# Generated by Django 5.0.7 on 2024-08-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_career_applications_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_agent',
            name='Id_no',
        ),
        migrations.RemoveField(
            model_name='applied_agent',
            name='Id_type',
        ),
        migrations.RemoveField(
            model_name='applied_agent',
            name='description',
        ),
    ]
