# Generated by Django 5.0.7 on 2024-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_remove_applied_agent_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_agent',
            name='applicant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
