# Generated by Django 5.0.7 on 2024-08-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_applied_agent_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applied_Agent',
        ),
    ]
